# Generated by Django 3.2.7 on 2022-02-20 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name Of Factory/Shop or Enterprise')),
                ('type', models.CharField(choices=[('FOOD', 'Agriculture industry'), ('AUTOMOBILE', 'Automobile Industry'), ('AI', 'Aerospace Industry'), ('TI', 'Transport Industry'), ('CI', 'IT Industry'), ('EI', 'Electronics Industry'), ('COI', 'Construction Industry'), ('TLI', 'Telecommunication industry')], max_length=128, verbose_name='Type of Indsutry')),
                ('address', models.CharField(max_length=128, verbose_name='Address of Factory')),
                ('no_workers', models.IntegerField(default=0, verbose_name='Number of Workers')),
            ],
            options={
                'verbose_name': 'Enterprise/Factory',
                'verbose_name_plural': 'Enterprises/Factories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Product to be manufactured/sold')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name Of Employee')),
                ('employee_salary', models.IntegerField(default=1000, verbose_name='Enter Salary of Employee(in Rs) per Month')),
                ('designation', models.CharField(max_length=128, verbose_name='Designation of Employees(like manager, accountant etc.')),
                ('profile_photo', models.ImageField(null=True, upload_to='', verbose_name='Image of Employee')),
                ('foctory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.factory', verbose_name='Factory name')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
