# Generated by Django 3.2.7 on 2022-02-20 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name of Inventory')),
                ('address', models.CharField(max_length=128, verbose_name='Address of Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='factory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Managed bu User'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='address',
            field=models.TextField(verbose_name='Address of Factory'),
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_lot_size', models.IntegerField(default=10, verbose_name='Maximum Volume/Lot size of Product')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.inventory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='industry.products', verbose_name='Product Name')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.factory', verbose_name='Enterprise/Factory'),
        ),
    ]
